# Generated by Django 4.2.23 on 2025-10-03 16:11

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Используется в URL. Заполнится автоматически.', unique=True, verbose_name='URL-slug')),
            ],
            options={
                'verbose_name': 'Категория статьи',
                'verbose_name_plural': 'Категории статей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Корзина пользователя',
                'verbose_name_plural': 'Корзины пользователей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория характеристики',
                'verbose_name_plural': 'Категории характеристик',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name="Название группы (например, 'Чехол для iPhone 15 Pro')")),
            ],
            options={
                'verbose_name': 'Группа цветов',
                'verbose_name_plural': 'Группы цветов',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', tinymce.models.HTMLField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше будет вопрос', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ (FAQ)',
                'verbose_name_plural': 'Вопросы-Ответы (FAQ)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InfoPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#444444', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона')),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет текста')),
            ],
            options={
                'verbose_name': 'Информационная панелька',
                'verbose_name_plural': 'Информационные панельки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('delivery_method', models.CharField(max_length=50, verbose_name='Способ доставки')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Населенный пункт')),
                ('district', models.CharField(blank=True, max_length=150, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=20, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='Квартира')),
                ('postcode', models.CharField(blank=True, max_length=6, verbose_name='Почтовый индекс')),
                ('cdek_office_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес пункта выдачи СДЭК')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (без скидки)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Размер скидки')),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('applied_rule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примененная скидка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обычная цена')),
                ('deal_price', models.DecimalField(blank=True, decimal_places=2, help_text="Укажите цену, которая будет действовать во время акции 'Товар дня'. Оставьте пустым, если скидки нет.", max_digits=10, null=True, verbose_name="Акционная цена ('Товар дня')")),
                ('deal_ends_at', models.DateTimeField(blank=True, help_text="Укажите дату и время окончания акции. После этого товар перестанет быть 'Товаром дня'.", null=True, verbose_name="Акция 'Товар дня' действует до")),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (виден клиенту)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('main_image', models.ImageField(upload_to='products/main/original/', verbose_name='Главное фото (оригинал)')),
                ('audio_sample', models.FileField(blank=True, null=True, upload_to='products/audio/', verbose_name='Пример аудио (MP3, WAV)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Категория')),
                ('color_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.colorgroup', verbose_name='Группа цветов')),
                ('info_panels', models.ManyToManyField(blank=True, to='shop.infopanel', verbose_name='Информационные панельки')),
                ('related_products', models.ManyToManyField(blank=True, to='shop.product', verbose_name='Сопутствующие товары')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название (для админа)')),
                ('image', models.ImageField(upload_to='banners/original/', verbose_name='Изображение (оригинал)')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='URL-ссылка (куда ведет баннер)')),
                ('text_content', models.CharField(blank=True, help_text='Оставьте пустым, если текст не нужен', max_length=150, verbose_name='Текст на баннере')),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Например, #FFFFFF для белого', max_length=7, verbose_name='Цвет текста (HEX)')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем левее будет баннер', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (виден клиенту)')),
            ],
            options={
                'verbose_name': 'Промо-баннер (сторис)',
                'verbose_name_plural': 'Промо-баннеры (сторис)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_username', models.CharField(default='username', help_text='Без @', max_length=100, verbose_name='Юзернейм менеджера в Telegram')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('about_us_section', tinymce.models.HTMLField(blank=True, help_text='Краткий рассказ о магазине', verbose_name="Блок 'О нас'")),
                ('delivery_section', tinymce.models.HTMLField(blank=True, verbose_name="Блок 'Условия доставки'")),
                ('warranty_section', tinymce.models.HTMLField(blank=True, verbose_name="Блок 'Гарантия и возврат'")),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Оставьте пустым или 0, чтобы отключить эту функцию', max_digits=10, null=True, verbose_name='Порог бесплатной доставки')),
                ('search_placeholder', models.CharField(default='Найти чехол или наушники...', max_length=150, verbose_name='Плейсхолдер в строке поиска')),
                ('search_initial_text', models.CharField(default='Начните вводить, чтобы найти товар', max_length=255, verbose_name='Текст до начала поиска')),
                ('search_lottie_file', models.FileField(blank=True, help_text='Отображается на пустой странице поиска', null=True, upload_to='lottie/', verbose_name='Файл Lottie-анимации (.json) для Поиска')),
                ('cart_lottie_file', models.FileField(blank=True, help_text='Отображается в пустой корзине', null=True, upload_to='lottie/', verbose_name='Файл Lottie-анимации (.json) для Корзины')),
                ('article_font_family', models.CharField(default='Exo 2', help_text="Например: 'Roboto', 'Times New Roman', 'Exo 2'", max_length=100, verbose_name='Название шрифта для статей')),
                ('privacy_policy', tinymce.models.HTMLField(blank=True, verbose_name='Политика конфиденциальности')),
                ('public_offer', tinymce.models.HTMLField(blank=True, verbose_name='Публичная оферта')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/original/', verbose_name='Изображение (оригинал)')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись (опционально)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shopsettings')),
            ],
            options={
                'verbose_name': 'Фотография магазина',
                'verbose_name_plural': 'Фотографии магазина',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductInfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок (под фото)')),
                ('image', models.ImageField(upload_to='products/info_cards/original/', verbose_name='Фото для карточки (оригинал)')),
                ('link_url', models.URLField(verbose_name='URL для перехода по клику')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Инфо-карточка (фича)',
                'verbose_name_plural': 'Инфо-карточки (фичи)',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/original/', verbose_name='Фото (оригинал)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент покупки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название особенности')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.product')),
            ],
            options={
                'verbose_name': 'Особенность (функционал)',
                'verbose_name_plural': 'Особенности (функционал)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название правила (для админа)')),
                ('discount_type', models.CharField(choices=[('TOTAL_QTY', 'На общее количество товаров в корзине'), ('PRODUCT_QTY', 'На количество конкретного товара'), ('CATEGORY_QTY', 'На количество товаров из конкретной категории')], default='TOTAL_QTY', max_length=20, verbose_name='Тип скидки')),
                ('min_quantity', models.PositiveIntegerField(default=2, verbose_name='Минимальное количество для активации')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Например, 10.5 для 10.5%', max_digits=5, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Правило активно')),
                ('category_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Целевая категория')),
                ('product_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Целевой товар')),
            ],
            options={
                'verbose_name': 'Правило скидки',
                'verbose_name_plural': 'Правила скидок',
                'ordering': ['-discount_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='shop.characteristiccategory')),
            ],
            options={
                'verbose_name': 'Характеристика (справочник)',
                'verbose_name_plural': 'Характеристики (справочник)',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(blank=True, help_text="Человекопонятный URL. Генерируется из заголовка, но можно отредактировать. Пример: 'kak-vybrat-naushniki'", max_length=220, unique=True, verbose_name='URL-slug')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('cover_image', models.ImageField(help_text='Будет отображаться в списке статей и при репосте в соцсети.', upload_to='articles/covers/', verbose_name='Обложка статьи (оригинал)')),
                ('content_type', models.CharField(choices=[('INTERNAL', 'Внутренняя статья'), ('EXTERNAL', 'Внешняя ссылка')], default='INTERNAL', max_length=10, verbose_name='Тип контента')),
                ('content', tinymce.models.HTMLField(blank=True, help_text="Для 'Внутренней статьи'. <b>ВАЖНО:</b> перед загрузкой изображений в редактор, сожмите их с помощью онлайн-сервисов (например, TinyPNG) до размера < 1 МБ.", verbose_name='Содержимое статьи')),
                ('external_url', models.URLField(blank=True, help_text="Для 'Внешней ссылки'. Укажите полный URL, например, https://example.com/article", verbose_name='URL внешней статьи')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликовано')], default='DRAFT', help_text="'Черновик' не виден пользователям, 'Опубликовано' - виден всем.", max_length=10, verbose_name='Статус')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок для вкладки браузера и поисковиков (до 60 символов). Если пусто, используется основной заголовок.', max_length=60, verbose_name='Meta Title (для SEO)')),
                ('meta_description', models.TextField(blank=True, help_text='Краткое описание для Google и Яндекс (до 160 символов). Очень важно для привлечения пользователей.', max_length=160, verbose_name='Meta Description (для SEO)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.articlecategory', verbose_name='Категория')),
                ('related_products', models.ManyToManyField(blank=True, help_text='Товары, которые будут рекомендоваться в конце статьи.', to='shop.product', verbose_name='Связанные товары')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.characteristic', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='shop.product')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
                'ordering': ['characteristic'],
                'unique_together': {('product', 'characteristic')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['added_at'],
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
