# Generated by Django 4.2.23 on 2025-10-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество просмотров'),
        ),
    ]
