# Generated by Django 4.2.23 on 2025-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_article_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Отметьте, чтобы статья отображалась в особых блоках (например, 'Статья дня').", verbose_name='Закрепленная статья'),
        ),
    ]
