# Generated by Django 4.2.23 on 2025-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_article_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='seo_description_blog',
            field=models.TextField(blank=True, default='Интересные статьи, обзоры и новости от {{site_name}}.', verbose_name='SEO Description для Блога'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_description_cart',
            field=models.TextField(blank=True, default='Оформите заказ на выбранные товары в {{site_name}}.', verbose_name='SEO Description для Корзины'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_description_checkout',
            field=models.TextField(blank=True, default='Заполните данные для завершения вашего заказа в {{site_name}}.', verbose_name='SEO Description для Оформления заказа'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_description_faq',
            field=models.TextField(blank=True, default='Ответы на частые вопросы, информация о доставке и гарантии от {{site_name}}.', verbose_name='SEO Description для Инфо/FAQ'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_description_home',
            field=models.TextField(blank=True, default='Лучшие гаджеты и аксессуары в {{site_name}}.', verbose_name='SEO Description для Главной'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_description_product',
            field=models.TextField(blank=True, default='Закажите {{product_name}} с доставкой. Лучшая цена: {{product_price}} ₽.', help_text='Доступные переменные: {{product_name}}, {{product_price}}, {{site_name}}', verbose_name='SEO Description для Товара'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_title_blog',
            field=models.CharField(blank=True, default='Блог | {{site_name}}', max_length=255, verbose_name='SEO Title для Блога'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_title_cart',
            field=models.CharField(blank=True, default='Ваша корзина | {{site_name}}', max_length=255, verbose_name='SEO Title для Корзины'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_title_checkout',
            field=models.CharField(blank=True, default='Оформление заказа | {{site_name}}', max_length=255, verbose_name='SEO Title для Оформления заказа'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_title_faq',
            field=models.CharField(blank=True, default='Информация и FAQ | {{site_name}}', max_length=255, verbose_name='SEO Title для Инфо/FAQ'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_title_home',
            field=models.CharField(blank=True, default='{{site_name}} | Главная', max_length=255, verbose_name='SEO Title для Главной'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='seo_title_product',
            field=models.CharField(blank=True, default='Купить {{product_name}} | {{site_name}}', help_text='Доступные переменные: {{product_name}}, {{product_price}}, {{site_name}}', max_length=255, verbose_name='SEO Title для Товара'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='site_name',
            field=models.CharField(default='BonaFide55', help_text='Используется в шаблонах мета-тегов как переменная {{site_name}}', max_length=50, verbose_name='Название сайта (для SEO)'),
        ),
    ]
