# Generated by Django 4.2.23 on 2025-12-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopsettings_seo_description_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Оставьте пустым для автоматической генерации.', max_length=20, null=True, unique=True, verbose_name='Артикул (SKU)'),
        ),
    ]
