# Generated by Django 4.2.23 on 2025-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Автоматический бэкап', max_length=255, verbose_name='Название / Комментарий')),
                ('file', models.FileField(help_text='Содержит базу данных и медиафайлы', upload_to='backups/', verbose_name='Файл архива (.zip)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
    ]
