# Generated by Django 4.2.23 on 2025-12-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название / Комментарий'),
        ),
    ]
