# Generated by Django 4.2.23 on 2025-12-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_backup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Session Key (UUID)'),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID пользователя'),
        ),
    ]
