# Generated by Django 4.2.23 on 2025-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_session_key_order_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID пользователя'),
        ),
    ]
