# Generated by Django 4.2.23 on 2025-12-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_cart_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='telegram_id',
        ),
    ]
