# Generated by Django 4.2.23 on 2025-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_cart_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID пользователя'),
        ),
    ]
