# Generated by Django 4.2.23 on 2025-12-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальная ссылка. Оставьте пустым для автогенерации из названия.', max_length=255, null=True, verbose_name='URL-slug'),
        ),
    ]
