# Generated by Django 4.2.23 on 2025-12-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальная ссылка. Оставьте пустым для автогенерации из названия.', max_length=255, unique=True, verbose_name='URL-slug'),
        ),
    ]
