# Generated by Django 4.2.23 on 2025-12-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Используется в Schema.org', null=True, upload_to='settings/', verbose_name='Логотип магазина'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='og_default_image',
            field=models.ImageField(blank=True, help_text='Картинка для соцсетей, если страница не имеет своей', null=True, upload_to='settings/', verbose_name='OG Image по умолчанию'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='telegram_channel_url',
            field=models.URLField(blank=True, help_text='Например: https://t.me/your_shop', verbose_name='Ссылка на Telegram канал/бот'),
        ),
    ]
