# Generated by Django 4.2.23 on 2025-12-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_white_label_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='manager_telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Для получения ID: отправьте /start боту, затем узнайте свой ID через @userinfobot. Сюда будут приходить уведомления о заказах.', null=True, verbose_name='Telegram Chat ID менеджера'),
        ),
    ]
