# Generated by Django 4.2.23 on 2025-12-29 12:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_add_manager_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text="Для 'Внутренней статьи'. <b>ВАЖНО:</b> перед загрузкой изображений в редактор, сожмите их с помощью онлайн-сервисов (например, TinyPNG) до размера < 1 МБ.", verbose_name='Содержимое статьи'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=tinymce.models.HTMLField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='about_us_section',
            field=tinymce.models.HTMLField(blank=True, help_text='Краткий рассказ о магазине', verbose_name="Блок 'О нас'"),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='delivery_section',
            field=tinymce.models.HTMLField(blank=True, verbose_name="Блок 'Условия доставки'"),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='privacy_policy',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='public_offer',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Публичная оферта'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='warranty_section',
            field=tinymce.models.HTMLField(blank=True, verbose_name="Блок 'Гарантия и возврат'"),
        ),
    ]
