# Generated by Django 4.2.23 on 2026-01-01 11:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_replace_ckeditor_with_tinymce'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Канонический URL страницы, если требуется переопределить.', verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='URL изображения для соцсетей. Если пусто, будет использовано cover_image.', verbose_name='Open Graph Image URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text="Для 'Внутренней статьи'. Изображения до 15 МБ автоматически оптимизируются при загрузке.", verbose_name='Содержимое статьи'),
        ),
    ]
