# Generated by Django 4.2.23 on 2026-01-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_article_canonical_url_article_og_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Оставьте пустым, если это оригинальная статья. Заполняйте ТОЛЬКО если это перепечатка (кросспостинг) — укажите здесь ссылку на первоисточник, чтобы избежать санкций поисковиков за дублирующийся контент.', verbose_name='Canonical URL'),
        ),
    ]
