# Generated by Django 4.2.23 on 2026-01-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_article_canonical_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='og_image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Персональная картинка для репостов. Если пусто, используется обложка статьи.', upload_to='articles/og/', verbose_name='Open Graph Image (для соцсетей)'),
        ),
    ]
