# Generated by Django 4.2.23 on 2026-01-11 13:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_enable_trigram'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'description'], name='product_search_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
