# Generated by Django 4.2.23 on 2026-01-11 13:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_product_search_gin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_search_gin',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
