# Generated by Django 4.2.23 on 2026-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_product_product_search_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='log',
            field=models.TextField(blank=True, verbose_name='Лог операций'),
        ),
        migrations.AddField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Создается...'), ('success', 'Готово'), ('failed', 'Ошибка')], default='success', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(blank=True, help_text='Содержит базу данных и медиафайлы', null=True, upload_to='backups/', verbose_name='Файл архива (.zip)'),
        ),
    ]
