# Generated by Django 4.2.23 on 2026-01-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_backup_log_backup_status_alter_backup_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='order_success_lottie_file',
            field=models.FileField(blank=True, help_text='Отображается после оформления заказа (галочка/салют)', null=True, upload_to='lottie/', verbose_name='Файл Lottie-анимации (.json) для Страницы Успеха'),
        ),
    ]
