# Generated by Django 4.2.23 on 2026-01-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_shopsettings_order_success_lottie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_backorder',
            field=models.BooleanField(default=False, help_text='Если включено, клиенты смогут купить товар, даже если на складе 0 (Backorder).', verbose_name='Разрешить покупку при 0 кол-ве'),
        ),
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('IN_STOCK', 'В наличии'), ('OUT_OF_STOCK', 'Нет в наличии'), ('PRE_ORDER', 'Предзаказ'), ('DISCONTINUED', 'Снят с производства'), ('ON_DEMAND', 'Под заказ')], default='IN_STOCK', help_text='Управляет логикой отображения кнопки покупки и бейджей.', max_length=20, verbose_name='Статус наличия'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=3, help_text="Если количество меньше или равно этому числу (и больше 0), клиент увидит предупреждение 'Осталось мало!'.", verbose_name="Порог 'Мало на складе'"),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_date',
            field=models.DateField(blank=True, help_text="Для товаров со статусом 'Предзаказ' или 'Под заказ'. Будет показана клиенту.", null=True, verbose_name='Ожидаемая дата поступления'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text="Реальное количество товара. Если 0 и статус 'В наличии', товар все равно может быть куплен (зависит от галочки 'Разрешить предзаказ при 0').", verbose_name='Количество на складе'),
        ),
    ]
