# Generated by Django 4.2.23 on 2026-01-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='search_initial_text',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='search_lottie_file',
        ),
    ]
