# Generated by Django manually
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_characteristicgroup_product_characteristic_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacteristicCategory',
            new_name='CharacteristicSection',
        ),
        migrations.AlterModelOptions(
            name='characteristicsection',
            options={'ordering': ['order'], 'verbose_name': 'Раздел характеристик', 'verbose_name_plural': 'Разделы характеристик'},
        ),
        migrations.RenameField(
            model_name='characteristic',
            old_name='category',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='shop.characteristicsection', verbose_name='Раздел'),
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'ordering': ['section__order', 'name'], 'verbose_name': 'Характеристика (справочник)', 'verbose_name_plural': 'Характеристики (справочник)'},
        ),
    ]
