# Generated by Django 4.2.23 on 2026-02-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rename_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название особенности')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.FileField(blank=True, help_text='Рекомендуется SVG для лучшего качества.', null=True, upload_to='features/icons/', verbose_name='Иконка (SVG/PNG)')),
                ('description', models.TextField(blank=True, verbose_name='Описание (для подсказок)')),
            ],
            options={
                'verbose_name': 'Справочник особенностей',
                'verbose_name_plural': 'Справочник особенностей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='characteristicsection',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(blank=True, help_text="Оставьте пустым, чтобы использовать название из справочника. ИЛИ напишите свое уточнение (напр. 'Быстрая зарядка 65W')", max_length=200, verbose_name='Переопределение названия'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='shop.featuredefinition', verbose_name='Особенность из справочника'),
        ),
    ]
