# Generated by Django 4.2.23 on 2026-02-02 09:35

from django.db import migrations
from pytils.translit import slugify

def migrate_features_forward(apps, schema_editor):
    Feature = apps.get_model('shop', 'Feature')
    FeatureDefinition = apps.get_model('shop', 'FeatureDefinition')

    # Get all existing features
    existing_features = Feature.objects.all()

    # Create definitions for unique names
    unique_names = set()
    for feature in existing_features:
        if feature.name:
            # Clean the name: simple strip and capitalization for consistency
            clean_name = feature.name.strip()
            unique_names.add(clean_name)
    
    name_map = {}
    for name in unique_names:
        # Create or Get definition
        definition, created = FeatureDefinition.objects.get_or_create(
            name=name,
            defaults={'slug': slugify(name)[:100]}
        )
        name_map[name] = definition

    # Link features to definitions
    for feature in existing_features:
        if feature.name:
            clean_name = feature.name.strip()
            if clean_name in name_map:
                feature.feature_definition = name_map[clean_name]
                feature.name = "" # Clear name as it matches definition. If we want to keep it as override, we would leave it, but standard practice is to clear if identical.
                # However, for safety, let's clear it ONLY if it perfectly matches the definition name.
                # Actually, in this pass, they DO match perfectly because we just created definitions from them.
                # So we clear it to switch to Dictionary mode.
                feature.save()

def migrate_features_backward(apps, schema_editor):
    Feature = apps.get_model('shop', 'Feature')
    # Restore names from definitions
    for feature in Feature.objects.all():
        if feature.feature_definition and not feature.name:
            feature.name = feature.feature_definition.name
            feature.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_featuredefinition_alter_characteristicsection_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_features_forward, migrate_features_backward),
    ]
