# Generated by Django 4.2.23 on 2026-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_migrate_data_to_feature_definitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityBlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID')),
                ('request_path', models.CharField(max_length=255, verbose_name='Путь запроса')),
                ('limit_type', models.CharField(help_text='Какой throttle class сработал', max_length=50, verbose_name='Сработал лимит')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата инцидента')),
            ],
            options={
                'verbose_name': '🛡 Журнал атак (429)',
                'verbose_name_plural': '🛡 Журнал атак (429)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('IP', 'IP адрес'), ('TG', 'Telegram ID')], default='IP', max_length=2, verbose_name='Тип блокировки')),
                ('value', models.CharField(help_text='IP адрес или Telegram ID', max_length=255, verbose_name='Значение')),
                ('reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': '⛔ Черный список',
                'verbose_name_plural': '⛔ Черный список',
                'unique_together': {('item_type', 'value')},
            },
        ),
    ]
