# Generated by Django 4.2.23 on 2026-02-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_securityblocklog_blacklisteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='auto_ban_enabled',
            field=models.BooleanField(default=True, help_text='Блокировать ли пользователей автоматически при частых атаках (429 ошибок)', verbose_name='Включить Авто-Бан'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='auto_ban_hours',
            field=models.PositiveIntegerField(default=1, help_text='За какое время считать нарушения (например, 15 нарушений за 1 час)', verbose_name='Период учета нарушений (часов)'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='auto_ban_threshold',
            field=models.PositiveIntegerField(default=15, help_text="Сколько раз нужно получить '429 Too Many Requests', чтобы попасть в Черный список", verbose_name='Порог блокировки (кол-во нарушений)'),
        ),
    ]
